### ISSUE TITLE
Задание 3-4-5 (а вообще говоря и 6)

### ISSUE THREAD

**Issue by ala-n** [AmbrosyonokMarina/UP4sem#3]
...
это таска-ждун, чтобы напомнить про то что Леши сокучились по обновлениям в репозитории Марины ))

**Comment by ala-n** [comment]
@AmbrosyonokMarina, 
! ! ! ! !
Похоже ждун откинется раньше чем Марина что-то начнет заливать в репозиторий...
А вообще если серьезно проблемы с зачётом намечаются...

**Comment by AmbrosyonokMarina** [comment]
Что на зачет нужно?
​
​Обязательно все лабы сдавать?​

**Comment by djadjka** [comment]
Yep
